### ISSUE TITLE
Improve bundle size

### ISSUE THREAD

**Issue by mohuk** [angular-pakistan/ngpakistan.com#4]
First render is very slow and is downloading a very heavy `vendor.js` file
![angular pakistan](https://user-images.githubusercontent.com/3163551/30796909-747d4b9a-a1ed-11e7-9e3d-03d3d65d09d3.jpg)

Running `ng build` on checkout
![screen shot 2017-09-25 at 11 43 00 am](https://user-images.githubusercontent.com/3163551/30796926-869db60c-a1ed-11e7-9c47-1a072ac94f6a.png)

There is a need to update `@angular/cli` and support AOT builds via `--prod` flag.

**Comment by afirdousi** [comment]
💯 that's a good one. Thanks for working on this @mohuk. I will look into it and deploy.
